# Generated by Django 5.1.6 on 2025-11-10 16:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome do Plano')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('duracao', models.IntegerField(default=30, verbose_name='Duração (dias)')),
            ],
            options={
                'verbose_name': 'Tipo de Plano',
                'verbose_name_plural': 'Tipos de Planos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('lichess_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Lichess')),
                ('lichess_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Acesso')),
                ('is_lichess_connected', models.BooleanField(default=False, verbose_name='Conectado ao Lichess')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_custom_set', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_custom_permissions_set', to='auth.permission', verbose_name='Permissões')),
                ('tipo_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tiposplano', verbose_name='Tipo de Plano')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LichessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Lichess')),
                ('bullet_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Bullet')),
                ('bullet_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Bullet')),
                ('blitz_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Blitz')),
                ('blitz_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Blitz')),
                ('rapid_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Rapid')),
                ('rapid_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Rapid')),
                ('classical_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Classical')),
                ('classical_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Classical')),
                ('puzzles_solved', models.IntegerField(blank=True, null=True, verbose_name='Problemas Resolvidos')),
                ('puzzles_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating de Problemas')),
                ('lichess_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Usuário')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='País')),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='Título')),
                ('patron', models.BooleanField(default=False, verbose_name='Patrono do Lichess')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em (Lichess)')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Última vez visto')),
                ('play_time_total', models.IntegerField(blank=True, null=True, verbose_name='Tempo total de jogo (segundos)')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='URL do Perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_at_local', models.DateTimeField(auto_now_add=True, verbose_name='Criado em (local)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Lichess',
                'verbose_name_plural': 'Perfis do Lichess',
            },
        ),
    ]
