# Generated by Django 5.1.6 on 2025-09-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustom',
            name='is_lichess_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_rating_blitz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_rating_bullet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_rating_classical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='lichess_rating_rapid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
