# Generated by Django 5.1.6 on 2026-03-25 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_data_nascimento_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='is_lichess_connected',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_access_token',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_id',
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='chesscom_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário Chess.com'),
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='is_chesscom_connected',
            field=models.BooleanField(default=False, verbose_name='Conectado ao Chess.com'),
        ),
        migrations.CreateModel(
            name='ChessComProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chesscom_username', models.CharField(max_length=100, unique=True, verbose_name='Usuário Chess.com')),
                ('bullet_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Bullet')),
                ('bullet_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Bullet')),
                ('blitz_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Blitz')),
                ('blitz_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Blitz')),
                ('rapid_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Rapid')),
                ('rapid_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Rapid')),
                ('daily_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Daily')),
                ('daily_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Daily')),
                ('tactics_highest', models.IntegerField(blank=True, null=True, verbose_name='Tactics (maior rating)')),
                ('puzzle_rush_best', models.IntegerField(blank=True, null=True, verbose_name='Puzzle Rush (melhor score)')),
                ('fide_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating FIDE')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='URL do Perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_at_local', models.DateTimeField(auto_now_add=True, verbose_name='Criado em (local)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Chess.com',
                'verbose_name_plural': 'Perfis do Chess.com',
            },
        ),
        migrations.DeleteModel(
            name='LichessProfile',
        ),
    ]
