# Generated by Django 5.1.6 on 2025-09-21 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_usuariocustom_is_lichess_connected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposplano',
            options={'verbose_name': 'Tipo de Plano', 'verbose_name_plural': 'Tipos de Planos'},
        ),
        migrations.AlterModelOptions(
            name='usuariocustom',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_rating_blitz',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_rating_bullet',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_rating_classical',
        ),
        migrations.RemoveField(
            model_name='usuariocustom',
            name='lichess_rating_rapid',
        ),
        migrations.AlterField(
            model_name='tiposplano',
            name='duracao',
            field=models.IntegerField(default=30, verbose_name='Duração (dias)'),
        ),
        migrations.AlterField(
            model_name='tiposplano',
            name='nome',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='tiposplano',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_custom_set', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='is_lichess_connected',
            field=models.BooleanField(default=False, verbose_name='Conectado ao Lichess'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='lichess_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Acesso'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='lichess_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Lichess'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='tipo_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tiposplano', verbose_name='Tipo de Plano'),
        ),
        migrations.AlterField(
            model_name='usuariocustom',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_custom_permissions_set', to='auth.permission', verbose_name='Permissões'),
        ),
        migrations.CreateModel(
            name='LichessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Lichess')),
                ('bullet_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Bullet')),
                ('bullet_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Bullet')),
                ('blitz_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Blitz')),
                ('blitz_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Blitz')),
                ('rapid_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Rapid')),
                ('rapid_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Rapid')),
                ('classical_games_played', models.IntegerField(blank=True, null=True, verbose_name='Jogos Classical')),
                ('classical_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Classical')),
                ('puzzles_solved', models.IntegerField(blank=True, null=True, verbose_name='Problemas Resolvidos')),
                ('puzzles_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating de Problemas')),
                ('lichess_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Usuário')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='País')),
                ('title', models.CharField(blank=True, max_length=10, null=True, verbose_name='Título')),
                ('patron', models.BooleanField(default=False, verbose_name='Patrono do Lichess')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Criado em (Lichess)')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Última vez visto')),
                ('play_time_total', models.IntegerField(blank=True, null=True, verbose_name='Tempo total de jogo (segundos)')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='URL do Perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_at_local', models.DateTimeField(auto_now_add=True, verbose_name='Criado em (local)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Lichess',
                'verbose_name_plural': 'Perfis do Lichess',
            },
        ),
    ]
