# Generated by Django 5.1.6 on 2026-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_add_rating_fexerj'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='bolsista',
            field=models.BooleanField(default=False, help_text='Bolsistas não pagam mensalidade e não entram nos relatórios financeiros.', verbose_name='Bolsista'),
        ),
    ]
