# Generated by Django 5.1.6 on 2026-02-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_add_bolsista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='categoria_cbx',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria CBX'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Rua'),
        ),
    ]
