# Generated by Django 5.1.6 on 2026-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_categoria_cbx_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o sócio é excluído (soft delete).', null=True, verbose_name='Excluído em'),
        ),
    ]
