# Generated by Django 5.1.6 on 2026-03-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_add_soft_delete_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('suspenso', 'Suspenso'), ('inativo', 'Inativo'), ('pendente_pagamento', 'Aguardando Pagamento')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CobrancaAbacatePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(max_length=120, unique=True, verbose_name='ID da Cobrança (AbacatePay)')),
                ('billing_url', models.URLField(verbose_name='URL de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranças_abacatepay', to='socios.socio', verbose_name='Sócio')),
            ],
            options={
                'verbose_name': 'Cobrança AbacatePay',
                'verbose_name_plural': 'Cobranças AbacatePay',
                'ordering': ['-created_at'],
            },
        ),
    ]
