# Generated by Django 5.1.6 on 2025-11-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('tournament_type', models.CharField(choices=[('arena', 'Arena'), ('swiss', 'Suíço'), ('round_robin', 'Round Robin'), ('internal_swiss', 'Suíço (Interno)'), ('internal_round_robin', 'Round Robin (Interno)')], max_length=20, verbose_name='Tipo')),
                ('tournament_speed', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rápido'), ('classical', 'Clássico')], max_length=20, verbose_name='Velocidade')),
                ('clock_limit', models.IntegerField(verbose_name='Tempo Inicial (minutos)')),
                ('clock_increment', models.IntegerField(verbose_name='Incremento (segundos)')),
                ('minutes', models.IntegerField(verbose_name='Duração (minutos)')),
                ('start_time', models.DateTimeField(verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('created', 'Criado no Lichess'), ('in_progress', 'Em Andamento'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lichess_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False, verbose_name='Torneio Privado')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Senha')),
                ('min_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Mínimo')),
                ('max_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Máximo')),
                ('current_round', models.IntegerField(default=0, verbose_name='Rodada Atual')),
                ('total_rounds', models.IntegerField(default=0, verbose_name='Total de Rodadas')),
                ('is_lichess', models.BooleanField(default=True, verbose_name='Torneio do Lichess')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('tiebreak_1', models.FloatField(default=0, help_text='Buchholz or Sonneborn-Berger')),
                ('tiebreak_2', models.FloatField(default=0, help_text='Direct encounter')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.tournament')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-score', '-tiebreak_1', '-tiebreak_2'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('result', models.CharField(choices=[('pending', 'Pendente'), ('white_win', 'Vitória Brancas'), ('black_win', 'Vitória Pretas'), ('draw', 'Empate'), ('forfeit_white', 'WO Brancas'), ('forfeit_black', 'WO Pretas')], default='pending', max_length=15)),
                ('board_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_matches', to='main.participant')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_matches', to='main.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.tournament')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['round_number', 'board_number'],
                'unique_together': {('tournament', 'round_number', 'black_player'), ('tournament', 'round_number', 'white_player'), ('tournament', 'white_player', 'black_player', 'round_number')},
            },
        ),
    ]
