# Generated by Django 5.1.6 on 2025-09-21 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Torneio')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('tournament_type', models.CharField(choices=[('arena', 'Arena'), ('swiss', 'Suíço')], max_length=10, verbose_name='Tipo de Torneio')),
                ('clock_limit', models.IntegerField(help_text='Tempo inicial em minutos', verbose_name='Tempo Inicial')),
                ('clock_increment', models.IntegerField(help_text='Incremento em segundos', verbose_name='Incremento')),
                ('minutes', models.IntegerField(help_text='Duração do torneio em minutos', verbose_name='Duração')),
                ('tournament_speed', models.CharField(choices=[('ultraBullet', 'Ultra Bullet'), ('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rápido'), ('classical', 'Clássico')], max_length=20, verbose_name='Velocidade do Torneio')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Início')),
                ('lichess_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Lichess')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_private', models.BooleanField(default=False, verbose_name='Torneio Privado')),
                ('min_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Mínimo')),
                ('max_rating', models.IntegerField(blank=True, null=True, verbose_name='Rating Máximo')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('created', 'Criado no Lichess'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-start_time'],
            },
        ),
    ]
