# Generated by Django 5.1.6 on 2026-03-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-score'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tiebreak_1',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tiebreak_2',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_rounds',
        ),
    ]
