# Generated by Django 5.1.6 on 2026-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Inscrição'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize',
            field=models.TextField(blank=True, verbose_name='Premiação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tournament_rules/', verbose_name='Regulamento (PDF)'),
        ),
    ]
