# Generated by Django 5.1.6 on 2026-03-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tournament_price_tournament_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Pagamento Confirmado'),
        ),
    ]
