# Generated by Django 5.1.6 on 2026-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_participant_payment_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_lichess',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='lichess_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Link Externo do Torneio'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Torneio Online'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('created', 'Criado'), ('in_progress', 'Em Andamento'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
