# Generated by Django 5.1.6 on 2026-05-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
